### ISSUE TITLE
Bug chord C(9)

### ISSUE THREAD

**Issue by black00019** [More-Than-Solitaire/Tabs-Lite#85]
Hi i have the latest version of Tabs Lite 3.3.9
In this Tabs:
https://tabslite.com/tab/2343481 "Maledette malelingue by Ivan Graziani"
is presente a chord name "C(9)" but i when click not open chord

thanks

**Comment by cullub** [comment]
This is a partial issue.  The main issue here is that the tab author entered `C(9)` instead of `C9`, which is incorrect syntax.  However, the other issue is that the app didn't-find-a-chord response is just the circle spinner forever.

Todo:

- [ ] Set a chord-load timeout with an error message
- [ ] Maybe provide a link to similar chords if that happens?
- [ ] Maybe remove parentheses from chord names?  Don't really want to mess with chord names though.
